meta_title: "Juliette Lacroix, des parfums d'exception"
meta_description: "Découvrez votre prochain parfum grâce à une exéprience olfactive unique"
meta_image: "femme_sourire.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@juliettelacroix" # indispensable pour les Twitter Cards
