# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30c365af4d54f009481753fe9ed89a3e02c402b5f126167fa37ff06018921d890ffe5f177104a2a3fc06448590afe2ee16151021ca1f2ad8a4b3c87f8c1122ea

test:
  secret_key_base: a0bea3e5193f14fe1e64820f1bfa46791b939f421fdc94cb7984e2bbb96b3e85598c7cf1547e7947165cc58db5981e05cac7cd185c33f27c0528e7da31ddb390

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
